"""Change occupation to array in Ser

Revision ID: 0c365f15dbe6
Revises: c8433b570530
Create Date: 2024-08-07 15:06:57.471484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c365f15dbe6'
down_revision = 'c8433b570530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'occupations',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'occupations',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###
