"""Change occupation to array in Service mo

Revision ID: a612f27b43f7
Revises: f0ca78c99b15
Create Date: 2024-08-07 14:09:12.728932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a612f27b43f7'
down_revision = 'f0ca78c99b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('occupation', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'occupation')
    # ### end Alembic commands ###
