"""Add username column to service

Revision ID: bf00c3326db3
Revises: 71262b19794d
Create Date: 2024-05-23 13:46:23.318204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf00c3326db3'
down_revision = '71262b19794d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        # Añadir la columna con un valor por defecto temporal
        batch_op.add_column(sa.Column('username', sa.String(length=50), server_default='default_username', nullable=False))
        batch_op.add_column(sa.Column('comments', sa.ARRAY(sa.String()), nullable=True))

    # Actualizar los registros existentes con un valor adecuado
    op.execute('UPDATE service SET username = (SELECT username FROM "user" WHERE "user".id = service.user_id)')

    # Eliminar el valor por defecto temporal
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('username', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('comments')
        batch_op.drop_column('username')
    # ### end Alembic commands ###
