"""Change user fecha

Revision ID: c3cb637c62c9
Revises: 003c723883cd
Create Date: 2024-08-08 16:27:27.542506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cb637c62c9'
down_revision = '003c723883cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('available_times', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'available_times')
    # ### end Alembic commands ###
