"""Change occupation to array in Sere

Revision ID: c8433b570530
Revises: 37b69f904e2c
Create Date: 2024-08-07 15:02:48.085197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8433b570530'
down_revision = '37b69f904e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'occupations',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'occupations',
               existing_type=mysql.JSON(),
               nullable=False)
    # ### end Alembic commands ###
