"""Agregando campo 'occupation' al modelo Service

Revision ID: dc478fe11f6c
Revises: f7a64cb8be9e
Create Date: 2024-06-03 23:41:46.703819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc478fe11f6c'
down_revision = 'f7a64cb8be9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('occupation', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'occupation')
    # ### end Alembic commands ###
