"""Change occupation to array in Service mod222el

Revision ID: ff184daee5ec
Revises: 695c3e9d5ad4
Create Date: 2024-08-05 18:16:50.722136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff184daee5ec'
down_revision = '695c3e9d5ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'occupation',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_column('service', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('image_url', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('service', 'occupation',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
